"""Initial baseline

Revision ID: 4ee00300bc9f
Revises: 
Create Date: 2026-04-18 23:18:20.175799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee00300bc9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('lesson_num', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('teacher', sa.Text(), nullable=True),
    sa.Column('room', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_queue_status_created', 'notification_queue', ['status', 'created_at'], unique=False)
    op.create_index('idx_notification_queue_user_status', 'notification_queue', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_notification_queue_created_at'), 'notification_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_queue_group_name'), 'notification_queue', ['group_name'], unique=False)
    op.create_index(op.f('ix_notification_queue_status'), 'notification_queue', ['status'], unique=False)
    op.create_index(op.f('ix_notification_queue_user_id'), 'notification_queue', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), server_default='ru', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.add_column('schedule', sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('schedule', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.add_column('schedule', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('schedule', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('schedule', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('schedule', 'is_change',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'is_change',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('schedule', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('schedule', 'updated_at')
    op.drop_column('schedule', 'version')
    op.drop_column('schedule', 'updated_by')
    op.drop_column('schedule', 'is_published')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_notification_queue_user_id'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_status'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_group_name'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_created_at'), table_name='notification_queue')
    op.drop_index('idx_notification_queue_user_status', table_name='notification_queue')
    op.drop_index('idx_notification_queue_status_created', table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_table('base_schedule')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
