"""add subgroup support

Revision ID: e97d6903181c
Revises: c2763694de85
Create Date: 2026-04-18 23:46:29.318859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97d6903181c'
down_revision: Union[str, Sequence[str], None] = 'c2763694de85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_schedule_legacy")
    op.execute("DROP TABLE IF EXISTS audit_logs")
    op.execute("DROP TABLE IF EXISTS base_schedule")
    op.execute("DROP TABLE IF EXISTS notification_queue")
    op.execute("DROP TABLE IF EXISTS user_profiles")
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('lesson_num', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('teacher', sa.Text(), nullable=True),
    sa.Column('room', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.create_index('idx_notification_queue_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_notification_queue_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_queue_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_queue_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('subgroup', sa.Integer(), server_default='0', nullable=False),
    sa.Column('language', sa.Text(), server_default='ru', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    with op.batch_alter_table('schedule_legacy', schema=None) as batch_op:
        # Add missing columns as nullable to avoid integrity errors during batch migration
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        # Logic for altering columns if needed
        batch_op.alter_column('is_change',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_legacy', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_change',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.drop_table('user_profiles')
    with op.batch_alter_table('notification_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_queue_status'))
        batch_op.drop_index(batch_op.f('ix_notification_queue_group_name'))
        batch_op.drop_index(batch_op.f('ix_notification_queue_created_at'))
        batch_op.drop_index('idx_notification_queue_user_status')
        batch_op.drop_index('idx_notification_queue_status_created')

    op.drop_table('notification_queue')
    op.drop_table('base_schedule')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
